version: 0.2
phases:
  install:
    commands:
      - snap install yq
  pre_build:
    commands:
      - echo Logging into ECR
      - aws --version
      - eval $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - CONTAINER_NAME=mist
      - CONTAINER_PORT=2004
      - CAPACITY_PROVIDER_NAME="mist-cap-provider"
  build:
    commands:
      - echo Build started at `date`
      - echo Building the Docker image...
      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME
      - docker pull $REPO_URI:latest || true
      - sbt -DscalaVersion=2.12.7 -DsparkVersion=3.0.1 -DimagePath=$REPO_URI:latest docker
      - echo sbt build succeeded
      - docker tag $REPO_URI:latest $REPO_URI:latest
      - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG
      - ./cicd/configure-access.sh arn:aws:iam::535116412216:role/codedeploy-mist dev
      - aws ecs describe-task-definition --task-definition mist --profile dev | jq '.taskDefinition' | tee dev-taskdef.json
      - ./cicd/configure-access.sh arn:aws:iam::659908802543:role/codedeploy-mist staging
      - aws ecs describe-task-definition --task-definition mist --profile staging | jq '.taskDefinition' | tee staging-taskdef.json
      - ./cicd/configure-access.sh arn:aws:iam::410422127778:role/codedeploy-mist production
      - aws ecs describe-task-definition --task-definition mist --profile production | jq '.taskDefinition' | tee production-taskdef.json
      - echo Writing image definitions...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$TASK_NAME" "$REPO_URI:$IMAGE_TAG" | tee imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - dev-taskdef.json
    - staging-taskdef.json
    - production-taskdef.json